services:
  - type: web
    name: financial-ai
    env: python
    buildCommand: |
      python3.10 -m pip install -r requirements.txt
      python3.10 -c "import sys; print('Python version:', sys.version)"
    startCommand: ./simple_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        value: sqlite:///instance/app.db
